name: Trigger Repo B Pipeline

on:
  push:
    branches:
      - main

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check for newly added installer files
        id: check
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            BASE_SHA="${{ github.event.pull_request.base.sha }}"
            HEAD_SHA="${{ github.event.pull_request.head.sha }}"
          else
            # For push events
            BASE_SHA=$(git rev-parse HEAD~1)
            HEAD_SHA=$(git rev-parse HEAD)
          fi
          echo "BASE_SHA=$BASE_SHA" >> $GITHUB_OUTPUT
          echo "HEAD_SHA=$HEAD_SHA" >> $GITHUB_OUTPUT
      - name: Trigger Repo B workflow
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.REPO_B_TOKEN }} # PAT with `repo` + `workflow` scopes
          repository: arin1984cloud/repo_b_test
          event-type: run-ci-cd
          client-payload: |
            {
              "ref": "${{ github.sha }}",
              "branch": "${{ github.ref_name }}",
              "base_sha": "${{ steps.check.outputs.BASE_SHA }}",
              "head_sha": "${{ steps.check.outputs.HEAD_SHA }}"
            }
